<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

/**
 * A Vorgang (case) is the structured form of one Kobo submission.
 *
 * The field set mirrors the reference monitor application
 * (invasive-pflanzen-monitor.html / invasive-pflanzen-stand.json), so existing
 * cases can be imported without losing any office work.
 *
 * Named in German to match the UI's domain language, and because `cases` is a
 * reserved word in SQL.
 */
return new class extends Migration
{
    public function up(): void
    {
        Schema::create('vorgaenge', function (Blueprint $table): void {
            $table->id();

            // Office-facing sequential case number, format N-000001 (localNr).
            $table->string('local_nr', 16)->nullable()->unique();

            // Generated by the public map screen (NEO-<base36 time>-<random>) and
            // carried through Kobo. Empty for submissions that never passed the
            // map screen, so it cannot be the primary identifier.
            $table->string('melde_id')->nullable()->unique();

            $table->foreignId('kobo_submission_id')->nullable()
                ->constrained('kobo_submissions')->nullOnDelete();

            $table->foreignId('status_id')
                ->constrained('workflow_statuses')->restrictOnDelete();

            // --- Angaben der meldenden Person ----------------------------
            $table->string('reported_species_raw')->nullable();
            $table->foreignId('species_id')->nullable()
                ->constrained('species')->nullOnDelete();

            // "Kennst du die Pflanzenart?"
            $table->string('knows_species')->nullable();

            // Free-text join of the selected location types.
            $table->string('location_summary', 512)->nullable();

            // "Wie groß ist der Pflanzenbestand ungefähr?"
            $table->string('size_category')->nullable();

            $table->text('citizen_note')->nullable();
            $table->text('citizen_risk_summary')->nullable();

            // The six risk questions as answered by the citizen.
            $table->json('risk_flags')->nullable();

            // --- Bewertung durch die Verwaltung ---------------------------
            // The same six options, assessed by the office. Drives the priority.
            $table->json('editor_risk')->nullable();

            // Computed from editor_risk; priority_override wins when set.
            $table->string('priority', 32)->default('Normal');
            $table->string('priority_override', 32)->nullable();

            $table->text('editor_note')->nullable();
            $table->boolean('confirmed')->default(false);
            $table->boolean('visited')->default(false);
            $table->date('visit_date')->nullable();

            // '' | Ja | Nein | Zu prüfen
            $table->string('action_needed', 32)->nullable();
            $table->text('measure')->nullable();

            // Free-text editor name from the legacy monitor, kept for imported
            // records where no matching user account exists.
            $table->string('editor_name')->nullable();

            // --- Geometrie ------------------------------------------------
            $table->string('geometry_type', 16)->nullable();
            $table->decimal('latitude', 10, 7)->nullable();
            $table->decimal('longitude', 10, 7)->nullable();
            $table->json('geojson')->nullable();

            // --- Reverse-Geocoding (Nominatim) ----------------------------
            $table->string('geo_label')->nullable();
            $table->string('geo_plz', 16)->nullable();
            $table->string('geo_ort')->nullable();
            $table->string('geo_kreis')->nullable();
            $table->boolean('geo_failed')->default(false);

            // --- Kontakt --------------------------------------------------
            // Kobo asks for contact in ONE free-text field; email and phone are
            // derived from it and the raw answer is kept verbatim.
            $table->string('reporter_name')->nullable();
            $table->string('reporter_contact_raw')->nullable();
            $table->string('reporter_email')->nullable();
            $table->string('reporter_phone')->nullable();
            $table->boolean('reporter_contact_consent')->default(false);

            $table->timestamp('submitted_at')->nullable();
            $table->boolean('captured_offline')->default(false);

            // --- Bearbeitung ---------------------------------------------
            $table->foreignId('assigned_to_id')->nullable()
                ->constrained('users')->nullOnDelete();
            $table->foreignId('assigned_by_id')->nullable()
                ->constrained('users')->nullOnDelete();
            $table->timestamp('assigned_at')->nullable();
            $table->date('due_date')->nullable();

            $table->timestamp('closed_at')->nullable();
            $table->foreignId('closed_by_id')->nullable()
                ->constrained('users')->nullOnDelete();

            $table->timestamps();
            $table->softDeletes();

            $table->index(['status_id', 'created_at']);
            $table->index(['assigned_to_id', 'status_id']);
            $table->index('submitted_at');
            $table->index('priority');
            $table->index(['geo_kreis', 'geo_plz']);
        });

        // Close the circular reference now that vorgaenge exists.
        Schema::table('kobo_submissions', function (Blueprint $table): void {
            $table->foreign('vorgang_id')->references('id')->on('vorgaenge')->nullOnDelete();
        });
    }

    public function down(): void
    {
        Schema::table('kobo_submissions', function (Blueprint $table): void {
            $table->dropForeign(['vorgang_id']);
        });

        Schema::dropIfExists('vorgaenge');
    }
};
