<?php

namespace App\Jobs;

use App\Events\VorgangCreated;
use App\Models\KoboSubmission;
use App\Models\Vorgang;
use App\Models\WorkflowStatus;
use App\Services\Kobo\KoboSubmissionMapper;
use Illuminate\Contracts\Queue\ShouldQueue;
use Illuminate\Foundation\Queue\Queueable;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Log;
use RuntimeException;
use Throwable;

/**
 * Turns one stored raw submission into a Vorgang.
 *
 * Safe to run more than once: a submission that already produced a Vorgang is
 * skipped, so a replay after a mapping fix cannot duplicate cases.
 */
class ProcessKoboSubmission implements ShouldQueue
{
    use Queueable;

    public int $tries = 3;

    public array $backoff = [10, 60, 300];

    public function __construct(public readonly int $submissionId)
    {
    }

    public function handle(KoboSubmissionMapper $mapper): void
    {
        $submission = KoboSubmission::find($this->submissionId);

        if ($submission === null) {
            return;
        }

        if ($submission->vorgang_id !== null) {
            return;
        }

        $submission->increment('processing_attempts');

        try {
            $vorgang = DB::transaction(fn () => $this->createVorgang($submission, $mapper));
        } catch (Throwable $e) {
            $submission->markFailed($e->getMessage());

            Log::error('Kobo-Submission konnte nicht verarbeitet werden.', [
                'submission_id' => $submission->getKey(),
                'kobo_id' => $submission->kobo_id,
                'error' => $e->getMessage(),
            ]);

            throw $e;
        }

        $submission->markProcessed($vorgang);

        if ($submission->attachmentDescriptors() !== []) {
            FetchKoboAttachments::dispatch($submission->getKey());
        }

        if ($vorgang->latitude !== null && $vorgang->longitude !== null) {
            GeocodeVorgang::dispatch($vorgang->getKey());
        }

        VorgangCreated::dispatch($vorgang);
    }

    private function createVorgang(KoboSubmission $submission, KoboSubmissionMapper $mapper): Vorgang
    {
        $initial = WorkflowStatus::initial();

        if ($initial === null) {
            throw new RuntimeException(
                'Kein Initialstatus konfiguriert. Bitte einen Workflow-Status mit "is_initial" anlegen.'
            );
        }

        $attributes = $mapper->map($submission->payload ?? []);

        // The melde_id is generated by the public map screen. A submission that
        // never passed through it has none, and that is normal - the office
        // works with local_nr instead.
        $meldeId = $attributes['melde_id'] ?: null;

        // The same report may already exist because the legacy monitor state was
        // imported first. Adopt that record instead of creating a second case -
        // otherwise `kobo:sync` after an import silently doubles the workload.
        //
        // The Kobo submission id is the reliable link: offline submissions carry
        // no melde_id at all, so matching on that alone would miss them.
        $existing = Vorgang::query()
            ->whereNull('kobo_submission_id')
            ->where(function ($query) use ($submission, $meldeId): void {
                if ($submission->kobo_id !== null) {
                    $query->orWhere('kobo_id', $submission->kobo_id);
                }

                if ($meldeId !== null) {
                    $query->orWhere('melde_id', $meldeId);
                }
            })
            // Guard against matching everything when neither key is known.
            ->when($submission->kobo_id === null && $meldeId === null, fn ($q) => $q->whereRaw('1 = 0'))
            ->first();

        if ($existing !== null) {
            // Only fill in what the office has not already recorded; its own
            // work always wins over a re-read of the original submission.
            $existing->fill(array_filter(
                $attributes,
                fn (string $key) => blank($existing->{$key}),
                ARRAY_FILTER_USE_KEY,
            ));

            $existing->kobo_submission_id = $submission->getKey();
            $existing->kobo_id ??= $submission->kobo_id;
            $existing->save();

            return $existing;
        }

        if ($meldeId !== null && Vorgang::withTrashed()->where('melde_id', $meldeId)->exists()) {
            $meldeId = $meldeId.'-'.$submission->getKey();
        }

        return Vorgang::create(array_merge($attributes, [
            'melde_id' => $meldeId,
            'kobo_id' => $submission->kobo_id,
            'local_nr' => Vorgang::nextLocalNr(),
            'kobo_submission_id' => $submission->getKey(),
            'status_id' => $initial->getKey(),
        ]));
    }
}
